"""
Translation catalog for geoaddress config strings.

Auto-generated by: ./manage.py update_translation_catalog
Do not edit manually. Run update_translation_catalog after config changes.
"""

from django.utils.translation import gettext_lazy as _

# Strings from geoaddress config - used by makemessages for extraction

_("Additional address info (optional)")
_("Address type or place type")
_("Backend display name")
_("Building, apartment, floor (optional)")
_("City name")
_("Combined backend_name-reference ID")
_("Company, institution, or organization name")
_("Confidence score (0-100%)")
_("Country name")
_("County or administrative county")
_("Full formatted address string (2 lines)")
_("Full formatted address string (3 lines)")
_("Full formatted address string (aligned)")
_("Full formatted address string (full)")
_("House number")
_("ISO country code (e.g., FR, US, GB)")
_("Latitude coordinate (float)")
_("Locality, hamlet or isolated dwelling")
_("Longitude coordinate (float)")
_("Municipality or local administrative unit")
_("Neighbourhood, quarter, or district")
_("OpenStreetMap ID")
_("OpenStreetMap type")
_("PO Box")
_("Post office box number")
_("Postal/ZIP code")
_("Relevance score (0-100%)")
_("Simple backend name (e.g., nominatim)")
_("Small locality such as hamlet or isolated dwelling")
_("Sorting code")
_("Sorting code (e.g., CEDEX, BXX, etc.)")
_("Standardized administrative subdivision code (ISO 3166-2)")
_("State/region/province or administrative area")
_("State/region/province or administrative area code")
_("Street name")
_("Street number and name")
